### ISSUE TITLE
SRTファイルのD&Dの対応

### ISSUE THREAD

**Issue by Mr-Ojii** [reku-hakimite/srt_to_exo_from_go#3]
SRTファイルをexeにD&Dするだけで変換できる機能

## メリット
現在はconfigファイルにSRTのファイルパスを記載する方式を取っているが、
1. 対象ファイルを選択し、パスのコピー
2. configファイルを開き、パスを貼り付ける
3. そのままではバックスラッシュがエスケープと認識されてしまうため、バックスラッシュを追加する

という手順が必要である

D&DではSRTファイルを投げ込むだけで済むようになるため、作業の簡素化が可能となる

## 実装について
D&Dした際にはコマンドライン引数としてパスが展開されますので、os.Argsを用いればよいと推察されます

よろしくお願いいたします

**Comment by Hakimite-Reku** [comment]
なるほど、勉強になります

さっそく実装考えてみます、ありがとうございます

**Comment by Hakimite-Reku** [comment]
D&Dの実装が完了しましたのでIssueを閉じます
ありがとうございました！

## 実装方法
os.Executable(), filepath.Dir(), os.Chdir() でexeファイルの場所へ移動し

os.Args[1] よりコマンドラインからsrtファイルパスを取得

###### カレントディレクトリを変更し忘れてconfig.yamlが読めてなかったのが敗因でした
